apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/role
               operator: In
               values:
               - ssv-main
      containers:
      - name: ubuntu
        image: ubuntu
        imagePullPolicy: Always
        args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep infinity; done']
        resources:
          limits:
            cpu:  {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.mem }}
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists

