DefaultOpDelta: 4.0
DefaultAllocDelta: 0
Tests:
  - PackagePath: "./message/validation"
    TestCases:
      - Name: "VerifyRSASignature"
        OpDelta: 3.0
  - PackagePath: "./protocol/v2/types"
    TestCases:
      - Name: "VerifyBLS"
        OpDelta: 6.0
      - Name: "VerifyPKCS1v15"
        OpDelta: 3.0
      - Name: "VerifyPKCS1v15FastHash"
        OpDelta: 6.0
      - Name: "VerifyPSS"
        OpDelta: 4.0