DefaultOpDelta: 5.0
DefaultAllocDelta: 5.0
Packages:
  - Path: "./message/validation"
    Tests:
      - Name: "VerifyRSASignature"
        OpDelta: 10
  - Path: "./protocol/v2/ssv/queue"
    Tests:
      - Name: "BenchmarkPriorityQueue_Parallel"
        OpDelta: 5.0
      - Name: "BenchmarkPriorityQueue_Parallel_Lossy"
        OpDelta: 5.0
      - Name: "benchmarkPriorityQueueParallel"
        OpDelta: 5.0
      - Name: "BenchmarkPriorityQueue_Concurrent"
        OpDelta: 5.0
  - Path: "./protocol/v2/types"
    Tests:
      - Name: "VerifyBLS"
        OpDelta: 6.0
      - Name: "VerifyPKCS1v15"
        OpDelta: 4.0
      - Name: "VerifyPKCS1v15FastHash"
        OpDelta: 6.0
      - Name: "VerifyPSS"
      - Name: "BenchmarkVerifyPKCS1v15OpenSSL"
      - Name: "BenchmarkSignPKCS1v15OpenSSL"
