---
apiVersion: v1
kind: Service
metadata:
  name: node-d-1-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-d-1
spec:
  type: ClusterIP
  ports:
    - port: 12301
      protocol: UDP
      targetPort: 12301
      name: port-12301
    - port: 13301
      protocol: TCP
      targetPort: 13301
      name: port-13301
    - port: 15301
      protocol: TCP
      targetPort: 15301
      name: port-15301
    - port: 16301
      protocol: TCP
      targetPort: 16301
      name: port-16301
  selector:
    app: node-d-1
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: node-d-1
  name: node-d-1
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-d-1
  template:
    metadata:
      labels:
        app: node-d-1
    spec:
      containers:
      - name: node-d-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}        
        resources:
          limits:
            cpu:  {{ .Values.resources.limits_node_1.cpu }}
            memory: {{ .Values.resources.limits_node_1.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12301
          name: port-12301
          protocol: UDP
          hostPort: 12301            
        - containerPort: 13301
          name: port-13301
          hostPort: 13301
        - containerPort: 15301
          name: port-15301
          hostPort: 15301
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: SHARE_CONFIG
          value: {{ .Values.envs.SHARE_CONFIG }}
        - name: LOG_LEVEL
          value: {{ .Values.envs.LOG_LEVEL }}
        - name: DEBUG_SERVICES
          value: {{ .Values.envs.DEBUG_SERVICES }}
        - name: DISCOVERY_TYPE_KEY
          value: {{ .Values.envs.DISCOVERY_TYPE_KEY }}
        - name: NETWORK
          value: {{ .Values.envs.NETWORK }}
        - name: CONSENSUS_TYPE
          value: {{ .Values.envs.CONSENSUS_TYPE }}
        - name: HOST_DNS
          value: {{ .Values.envs.HOST_DNS }}
        - name: HOST_ADDRESS
          value: {{ .Values.envs.HOST_ADDRESS }}
        - name: LOGGER_LEVEL
          value: {{ .Values.envs.LOGGER_LEVEL }}
        - name: DB_PATH
          value: {{ .Values.envs.DB_PATH }}
        - name: DB_REPORTING
          value: {{ .Values.envs.DB_REPORTING }}
        - name: ENABLE_PROFILE
          value: {{ .Values.envs.ENABLE_PROFILE }}
        - name: DISCOVERY_TRACE
          value: {{ .Values.envs.DISCOVERY_TRACE }}
        - name: PUBSUB_TRACE
          value: {{ .Values.envs.PUBSUB_TRACE }}
        - name: P2P_LOG
          value: {{ .Values.envs.P2P_LOG }}
        - name: NETWORK_ID
          value: {{ .Values.envs.NETWORK_ID }}
        - name: GENESIS_EPOCH
          value: {{ .Values.envs.GENESIS_EPOCH }}
        - name: CLEAN_REGISTRY_DATA
          value: {{ .Values.envs.CLEAN_REGISTRY_DATA }}
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-1
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-d-1
      volumes:
      - name: ssv-node-v3-1
        persistentVolumeClaim:
          claimName: ssv-node-v3-1
      - name: ssv-cm-validator-options-ssv-node-cluster-d-1
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-d-1
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
