---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boot-node-3
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "ssv-3.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - boot-node-3
  http:
  - route:
    - destination:
        host: boot-node-3-svc
        port:
          number: 5003
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: boot-node-3
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "ssv-3.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: boot-node-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: boot-node-3
spec:
  type: ClusterIP
  ports:
    - port: 5680
      protocol: TCP
      targetPort: 5680
      name: port-5679
    - port: 4003
      protocol: UDP
      targetPort: 4003
      name: port-4003
    - port: 5003
      protocol: TCP
      targetPort: 5003
      name: port-5003
  selector:
    app: boot-node-3
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: boot-node-3
  name: boot-node-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boot-node-3
  template:
    metadata:
      labels:
        app: boot-node-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - ssv-boot-node
      containers:
      - name: boot-node-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-boot-node"]
        ports:
        - containerPort: 5003
          name: port-5003      
          hostPort: 5003
        env:
          - name: BOOT_NODE_PRIVATE_KEY
            value: "5e0b1cf218e644b91fdc9680be912279213b2985a10dea85f7b988216ac645b5"
          - name: BOOT_NODE_EXTERNAL_IP
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node_external_ip
          - name: TCP_PORT
            value: "5003"
          - name: UDP_PORT
            value: "4003"
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists         
      hostNetwork: true
