---
apiVersion: v1
kind: Service
metadata:
  name: node-c-4-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-c-4
spec:
  type: ClusterIP
  ports:
    - port: 12012
      protocol: UDP
      targetPort: 12012
      name: port-12012
    - port: 13012
      protocol: TCP
      targetPort: 13012
      name: port-13012
    - port: 15012
      protocol: TCP
      targetPort: 15012
      name: port-15012
  selector:
    app: node-c-4
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: node-c-4
  name: node-c-4
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-c-4
  template:
    metadata:
      labels:
        app: node-c-4
    spec:
      containers:
      - name: node-c-4
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        resources:
          limits:
            cpu:  {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.mem }}
        command: ["make", "start-node"]
        ports:
        - containerPort: 12012
          name: port-12012
          protocol: UDP
          hostPort: 12012            
        - containerPort: 13012
          name: port-13012
          hostPort: 13012
        - containerPort: 15012
          name: port-15012
          hostPort: 15012
        env:
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: SHARE_CONFIG
          value: {{ .Values.envs.SHARE_CONFIG }}
        - name: LOG_LEVEL
          value: {{ .Values.envs.LOG_LEVEL }}
        - name: DEBUG_SERVICES
          value: {{ .Values.envs.DEBUG_SERVICES }}
        - name: DISCOVERY_TYPE_KEY
          value: {{ .Values.envs.DISCOVERY_TYPE_KEY }}
        - name: NETWORK
          value: {{ .Values.envs.NETWORK }}
        - name: CONSENSUS_TYPE
          value: {{ .Values.envs.CONSENSUS_TYPE }}
        - name: HOST_DNS
          value: {{ .Values.envs.HOST_DNS }}
        - name: HOST_ADDRESS
          value: {{ .Values.envs.HOST_ADDRESS }}
        - name: DB_PATH
          value: "{{ .Values.envs.DB_PATH }}"
        - name: DB_REPORTING
          value: "{{ .Values.envs.DB_REPORTING }}"
        - name: ENABLE_PROFILE
          value: "{{ .Values.envs.ENABLE_PROFILE }}"
        - name: DISCOVERY_TRACE
          value: "{{ .Values.envs.DISCOVERY_TRACE }}"
        - name: PUBSUB_TRACE
          value: "{{ .Values.envs.PUBSUB_TRACE }}"
        - name: P2P_LOG
          value: "{{ .Values.envs.P2P_LOG }}"
        - name: NETWORK_ID
          value: "{{ .Values.envs.NETWORK_ID }}"
        - name: GENESIS_EPOCH
          value: "{{ .Values.envs.GENESIS_EPOCH }}"
        - name: CLEAN_REGISTRY_DATA
          value: "{{ .Values.envs.CLEAN_REGISTRY_DATA }}"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-12
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-c-4
      volumes:
      - name: ssv-node-12
        persistentVolumeClaim:
          claimName: ssv-node-12
      - name: ssv-cm-validator-options-ssv-node-cluster-c-4
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-c-4
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
