name: E2E Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - stage

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run e2e.sh
        env:
          BEACON_NODE_URL: ${{ secrets.E2E_BEACON_NODE_URL }}
          EXECUTION_NODE_URL: ${{ secrets.E2E_EXECUTION_NODE_URL }}
        run: |
          chmod +x ./e2e/run.sh
          ./e2e/run.sh

      - name: clean up
        run: docker compose down -v
