name: Update benchmarks in repo

on:
  workflow_dispatch:

jobs:
  update-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Tidy up dependencies
        run: go mod tidy

      - name: Update benchmarks
        run: |
          make update-benchmarks
